# Generated by Django 2.2.7 on 2021-06-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='display_emoji',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
